# Generated by Django 5.0.14 on 2025-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paratabledata_fixed_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_data',
            name='channel_fixed',
            field=models.IntegerField(default=0),
        ),
    ]
